// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID    `json:"id"`
	ClientID  uuid.UUID    `json:"client_id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Client struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	ApiKey    string       `json:"api_key"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
}
