// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateClient(ctx context.Context, arg CreateClientParams) error
	GetAccountByIDAndClientID(ctx context.Context, arg GetAccountByIDAndClientIDParams) (GetAccountByIDAndClientIDRow, error)
	GetAccountsByClientID(ctx context.Context, clientID uuid.UUID) ([]GetAccountsByClientIDRow, error)
	GetClientByAPIKey(ctx context.Context, apiKey string) (Client, error)
	GetClientByID(ctx context.Context, id uuid.UUID) (Client, error)
}

var _ Querier = (*Queries)(nil)
